### ISSUE TITLE
3.6.0-minimal lacks dependencies required by XSL-FO Module 

### ISSUE THREAD

**Issue by Sincopy** [evolvedbinary/docker-existdb#6] opened 2018-01-12 22:25 UTC
Calling xslfo:render() on 3.6.0-minimal causes an error to be thrown due to missing liblcms2.so.2.

**Comment by adamretter** [comment] 2018-01-14 15:06
Our images are based on Google Cloud Platform's "Distroless" images https://github.com/GoogleCloudPlatform/distroless

It looks like we would have to do quite some reconfiguration to generate an image using Bazel that includes the required Debian packages for Apache FOP - https://github.com/GoogleCloudPlatform/distroless#examples-with-bazel.

Is this something you would like to investigate?

**Comment by Sincopy** [comment] 2018-01-16 07:44
I'll have a look. I need to learn Bazel first, I guess. For others looking at this (or if someone can do the Bazel stuff quickly), I got it running my manually copying the following files from [OpenJDK 8 JDK Slim Docker](https://github.com/docker-library/openjdk/blob/a893fe3cd82757e7bccc0948c88bfee09bd916c3/8-jdk/slim/Dockerfile) image (JRE doesn't include these files, which I guess is exactly the issue):
- libfontmanager.so
- libjavalcms.so
- liblcms2.so.2
- libfreetype.so.6
- libpng16.so.16

There's even more dependencies if you want to use SVG inside XSL-FO.

btw. I expect that this issue applies also to the full 3.6.0 image as well as 3.6.1, since they also the distroless java image, which in turn uses the OpenJDK JRE 1.8.

**Comment by adamretter** [comment] 2018-02-14 12:59
Closed by https://github.com/evolvedbinary/docker-existdb/pull/7

**Closed as completed by adamretter** 2018-02-14 12:59 UTC

**Comment by duncdrum** [comment] 2018-05-13 12:07
@Sincopy exist-db is looking to step up its docker game. It would be great if you could help us to create a test for the xsl:fo and svg related issues to avoid regressions. 

Could you describe the steps necessary to reproduce the errors for FOP and what to look for with svg?
Thanks
